name: Build GBA artifact
on: [push]
jobs:
  Build-Docker-Image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker Image
        run: docker build .
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: GBA
          path: grooveboy.gba


